language: node_js
node_js: node
services: mongodb
script: ''
deploy:
  provider: heroku
  api_key: $secure
  app: dropbox-clone-api
  on:
    branch: master
    all_branches: false
    repo: joaaomanooel/dropbox-clone-api

