language: node_js
node_js: node
script: ''
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: dropbox-clone-api
  on:
    branch: master
    all_branches: false
    repo: joaaomanooel/dropbox-clone-api
