language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: ewexCaVBEHUfhTzQYGNc6Chf4GuVvepYRuXO7rgXa7HHVdVg41V3jLx4JcE3id3kqP8HmOAOBwyTQrVAyDziWkGmxAf7fIpErhSGGGCbJm6vuauPVrr3AFdzEL4v1YLDLxxf0mjhlRGZFLApz+Fwijpu5Vn1jFIfUAzyfzHqmDMkaMBF0CT7H99ec9RitZV3Idk/9Cy+XV0ZxktUXyLfwcwv6efGnL+JuNR7GbeotBYEwTVeN9tyevbcMThDw99ZIO/aocol1HpdXQ1KvWReNSaxOfRxnnng5LVlYBbOSHiJWpAObMwV5845XakgSq3B7rBDv7Z2xrn8Ntu12mhtvxUOY3vk5UMzmfXzpslxMkyP2wCNv/RgTqSC6qoU5wQs/MHqnPZ9TcnmoNYucmec8msNhzS+aYZAnmLP9AvMeKJFYzJOz3+ZbGxhOkCMd1435RULz1Z/7hUb5uGIkfJlR0SUst8f4SLDG0NmHxdBiQPsHlH7pmMNPqO/iYDdphzzUGqnlH0iIntwHLUoTP9De4MOZKx3V6T6gb8vZ0yUWMkFHT9jkTK6C94OmkM+XOxFJpZDFmNgkQMuq3wQJOeVYuUjt9sPNWXc47YjcBTRMWzv7Wvl6wb0Lzvg8ae9ze06bO0n8N82lM3pmNZoJCkuNwCEQuc2rVzpzy8L+B4zItQ=
  app: dropbox-clone-api
  on:
    repo: joaaomanooel/dropbox-clone-api
