language: node_js
node_js:
 - "10.15.1"
script:
  - "npm run lint"
  - "npm run test"
cache:
  directories:
    - node_modules
after_script: "cat ./coverage/lcov.info | coveralls"
deploy:
  provider: heroku
  api_key:
    secure: ab47a79d-51d5-419d-8c4b-aa5a5ce23906
  app: dropbox-clone-api
  on:
    branche: master
